### ISSUE TITLE
Users are not always getting confirmation emails after admin approves their account

### ISSUE THREAD

**Issue by bfreeds** [NYCPlanning/ceqr-app#533] opened 2020-01-08 17:14 UTC
Kasia reported that a user has experienced confusion about whether or not their account has been approved; apparently they have not received a confirmation email notifying them of the approval.

**Comment by bfreeds** [comment] 2020-01-15 16:47
Report that user tried to reset their password and did not receive an email for the reset.  See this Sentry log of the error:  https://sentry.io/organizations/nycplanning/issues/1170204825/?project=1366125&query=is%3Aunresolved

**Comment by hannahkates** [comment] 2020-01-15 21:15
Next steps:
- Start with looking at error log
- Try to replicate locally

**Comment by bfreeds** [comment] 2020-01-17 19:45
### Behavior with @planning.nyc.gov email domain (on ceqr-app production):
- [x] Created Account 
- [x] Received Account Activation Email
- [x] Validated Email and Logged In
- [x] Reset Password & Received Email
=> Works as expected

### Behavior with @gmail.com email domain:
- [x] Create Account ([`Auth::V1::UsersController#create`](https://github.com/NYCPlanning/ceqr-app/blob/bd64f741606be26b5c95d2ffc9546c2ce6c42e96/backend/app/controllers/auth/v1/users_controller.rb#L4)) ([Example Log](https://app.timber.io/nycplanning/logs/console?apps%5B0%5D=7153&id=570d4184-3951-11ea-ba02-121202d39601&date=2020-01-17T17%3A46%3A48.817249Z) 
- [ ] [`UserMailer > Account in Review`](https://github.com/NYCPlanning/ceqr-app/blob/bd64f741606be26b5c95d2ffc9546c2ce6c42e96/backend/app/mailers/user_mailer.rb#L10)([Example Log](https://app.timber.io/nycplanning/logs/console?apps%5B0%5D=7153&id=570e1a8c-3951-11ea-9120-121202d39601&date=2020-01-17T17%3A46%3A48.902564Z))
- [x] [`AdminMailer > Account in Review`](https://github.com/NYCPlanning/ceqr-app/blob/bd64f741606be26b5c95d2ffc9546c2ce6c42e96/backend/app/mailers/admin_mailer.rb#L2)([Example Log](https://app.timber.io/nycplanning/logs/console?apps%5B0%5D=7153&id=570e45d4-3951-11ea-b047-121202d39601&date=2020-01-17T17%3A46%3A48.904465Z))
- [x] [`Auth::V1::UsersController#approve`](https://github.com/NYCPlanning/ceqr-app/blob/bd64f741606be26b5c95d2ffc9546c2ce6c42e96/backend/app/controllers/auth/v1/users_controller.rb#L68) ([Example Log](https://app.timber.io/nycplanning/logs/console?apps%5B0%5D=7153&id=e9864fe2-3951-11ea-9361-12ce339d8163&date=2020-01-17T17%3A50%3A55.273449Z))
- [ ] [`UserMailer > Account Approved`](https://github.com/NYCPlanning/ceqr-app/blob/bd64f741606be26b5c95d2ffc9546c2ce6c42e96/backend/app/mailers/user_mailer.rb#L17)([Example Log](https://app.timber.io/nycplanning/logs/console?apps%5B0%5D=7153&id=e9872ba6-3951-11ea-830f-12ce339d8163&date=2020-01-17T17%3A50%3A55.284772Z))
- [x] Reset Password & Received Email

=> **User Email not send to notify of awaiting validation from admin & account approval.** After account was approved, able to log-in using the password used to create the account.  Able to receive email for password reset.   Tested this with a gmail domain with my personal email and Kasia's personal email.    

Looking at the Timber logs, the only evidence I see that there might be a failure in this process is [this 401 unauthorized](https://app.timber.io/nycplanning/logs/console?apps%5B0%5D=7153&id=9377a44e-395a-11ea-8c92-12ce339d8163&date=2020-01-17T18%3A52%3A55.569545Z) message after account approval.
![image](https://user-images.githubusercontent.com/5316367/72641322-dd7a8480-3937-11ea-87b2-8483e7b5d023.png)

The user who initially reported the email issue did not see a password reset.  Kasia is asking them to try it again and check if it got sent to spam.

**Comment by bfreeds** [comment] 2020-01-23 16:00
I'm not entirely sure how the email whitelist works, but suspect that this might be an area to investigate, considering the different behavior when using different email domains.  Confusingly, though, the person who reported having trouble was using a domain that _should_ be whitelisted, similar to our @planning.nyc.gov emails.

**Comment by bfreeds** [comment] 2020-02-10 18:44
A user with a `@planning.nyc.gov` (whitelisted) domain is experiencing an issue receiving an email validation.  This might be related to this larger app email issue.
![image](https://user-images.githubusercontent.com/5316367/74179412-67520080-4c0b-11ea-846c-ac3b4cc4fd46.png)

**Comment by bfreeds** [comment] 2020-02-25 19:52
On 2/10 Yijun received this notice on account signup:
![image.png](https://images.zenhubusercontent.com/5dd5a1e7efbeb900016c9ffd/64493a91-64e5-4bf9-8970-5030902c4150)

**Comment by allthesignals** [comment] 2020-03-05 19:23
Note: recall that I added a subscription to Mailgun at some point for this. We should make sure that payment is necessary and see if the logs provide any more information.

**Comment by allthesignals** [comment] 2020-06-25 20:47
gmail approval log

```
2020-06-25T20:36:50.796320+00:00 app[web.1]: Email: wmattgardner@gmail.com
2020-06-25T20:36:50.796321+00:00 app[web.1]: Click here to approve user: https://www.ceqr.app/signup/approve?token=
2020-06-25T20:36:50.796322+00:00 app[web.1]: 
2020-06-25T20:36:50.796322+00:00 app[web.1]: 
2020-06-25T20:36:50.796935+00:00 app[web.1]: [ActiveJob] [ActionMailer::Parameterized::DeliveryJob] [ad0a4e42-099c-4247-81d8-89b244e8f409] Performed ActionMailer::Parameterized::DeliveryJob (Job ID: ad0a4e42-099c-4247-81d8-89b244e8f409) from Async(mailers) in 408.26ms
2020-06-25T20:37:11.653825+00:00 heroku[router]: at=info method=OPTIONS path="/auth/v1/approve" host=api.ceqr.app request_id=35daee15-ccbe-4c97-a0e3-6c00e2c6ce1a fwd="24.228.122.173" dyno=web.1 connect=0ms service=3ms status=200 bytes=283 protocol=https
2020-06-25T20:37:11.687302+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae] Started PUT "/auth/v1/approve" for 24.228.122.173 at 2020-06-25 20:37:11 +0000
2020-06-25T20:37:11.689196+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae] Processing by Auth::V1::UsersController#approve as */*
2020-06-25T20:37:11.689282+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae]   Parameters: {"token"=>"xNTk1NzA5NDEwfQ.", "user"=>{}}
2020-06-25T20:37:11.765810+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae]   [1m[36mUser Load (3.7ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2[0m  [["email", "wmattgardner@gmail.com"], ["LIMIT", 1]]
2020-06-25T20:37:11.773706+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae]   [1m[35m (2.9ms)[0m  [1m[35mBEGIN[0m
2020-06-25T20:37:11.777731+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae]   [1m[36mUser Update (1.6ms)[0m  [1m[33mUPDATE "users" SET "email_validated" = $1, "account_approved" = $2, "updated_at" = $3 WHERE "users"."id" = $4[0m  [["email_validated", true], ["account_approved", true], ["updated_at", "2020-06-25 20:37:11.774864"], ["id", 475]]
2020-06-25T20:37:11.787938+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae]   [1m[35m (7.4ms)[0m  [1m[35mCOMMIT[0m
2020-06-25T20:37:11.791060+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae] [ActiveJob] Enqueued ActionMailer::Parameterized::DeliveryJob (Job ID: befd1553-6878-4baf-a280-1954aad510d6) to Async(mailers) with arguments: "UserMailer", "account_approved", "deliver_now", {:user=>#<GlobalID:0x0000557e84e0a698 @uri=#<URI::GID gid://labs-ceqr-api-rails/User/475>>}
2020-06-25T20:37:11.791807+00:00 app[web.1]: [bdb2bd5c-b893-4b2f-ad9c-d70c9c3aa0ae] Completed 200 OK in 102ms (Views: 0.3ms | ActiveRecord: 44.2ms)
2020-06-25T20:37:11.801775+00:00 app[web.1]:   [1m[36mUser Load (1.9ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 475], ["LIMIT", 1]]
2020-06-25T20:37:11.802825+00:00 app[web.1]: [ActiveJob] [ActionMailer::Parameterized::DeliveryJob] [befd1553-6878-4baf-a280-1954aad510d6] Performing ActionMailer::Parameterized::DeliveryJob (Job ID: befd1553-6878-4baf-a280-1954aad510d6) from Async(mailers) with arguments: "UserMailer", "account_approved", "deliver_now", {:user=>#<GlobalID:0x0000557e850ad800 @uri=#<URI::GID gid://labs-ceqr-api-rails/User/475>>}
2020-06-25T20:37:11.834573+00:00 app[web.1]: [ActiveJob] [ActionMailer::Parameterized::DeliveryJob] [befd1553-6878-4baf-a280-1954aad510d6]   Rendering user_mailer/account_approved.text.erb within layouts/mailer
2020-06-25T20:37:11.842586+00:00 app[web.1]: [ActiveJob] [ActionMailer::Parameterized::DeliveryJob] [befd1553-6878-4baf-a280-1954aad510d6]   Rendered user_mailer/account_approved.text.erb within layouts/mailer (0.9ms)
2020-06-25T20:37:11.844133+00:00 app[web.1]: [ActiveJob] [ActionMailer::Parameterized::DeliveryJob] [befd1553-6878-4baf-a280-1954aad510d6] UserMailer#account_approved: processed outbound mail in 20.6ms
```

**Comment by allthesignals** [comment] 2020-06-25 22:26
Just can't reproduce this... but have a working theory:

As @bfreeds pointed out, might have something to do with the AllowList we use here.

The call to this allow list creates a fork in the User creation method. The main difference is that disallowed users are put into a mailer `deliver_later` pool: https://api.rubyonrails.org/classes/ActionMailer/MessageDelivery.html#method-i-deliver_later

This creates an Active Job, and it could be that some jobs are failing for... reasons? It's hard to say. 

I need a specific user who's seeing this behavior... I could probably dig that up in the logs, but I'm unable to see the logs @bfreeds has linked to, for some reason.

**Comment by allthesignals** [comment] 2020-06-26 18:06
Closing for now until we get better information

**Closed** 2020-06-26 18:07 UTC
Labels: Greenskeeper, Sev2 Bug
